
server:
  port: 8090
spring:
  application:
    name: KCAUTH
  security:
    oauth2:
#      client:
#        registration:
#          keycloak:
#            client-id: food-ordering-client
#            client-secret: your-client-secret
#            scope: openid,profile,email
#            redirect-uri: http://localhost:8082/login/oauth2/code/keycloak
#        provider:
#          keycloak:
#            issuer-uri: http://localhost:8088/realms/food-ordering-realm
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:9090/realms/ms-cars/protocol/openid-connect/certs
          issuer-uri: http://localhost:9090/realms/ms-cars
#  jwt:
#    auth:
#      converter:
#        resource-id: ms-cars-client
#        principle-attribute: preferred_username
logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG